---
- hosts: all
  sudo: yes

  tasks:
  - name: Ensure that postgres.conf is correct
    copy: src=../templates/postgresql.conf dest=/etc/postgresql/9.1/main/postgresql.conf
    notify: restart postgresql

  - name: Ensure that pg_hba.conf is correct
    copy: src=../templates/pg_hba.conf dest=/etc/postgresql/9.1/main/pg_hba.conf
    notify: restart postgresql

  - meta: flush_handlers

  - name: Ensure that postgresql server is running
    service: name=postgresql state=started

  - name: Ensure that postgis_template database exists
    shell: /usr/share/pgrouting/workshop/bin/create_templates.sh

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

- hosts: all
  sudo: yes
  sudo_user: postgres
  vars_files:
    - ../vars.yml

  tasks:
  - name: Ensure that postgresql user '$db_user' exists
    postgresql_user: user=$db_user password=$db_user_pass

  - name: Ensure that all required databases exists
    postgresql_db: db={{ item.name }} template={{ item.template }} owner=$db_user
    with_items: $databases

  - name: Ensure that '$db_user' is owned of '$db_name'
    command: psql -d $db_name -c 'ALTER TABLE geometry_columns OWNER TO $db_user; ALTER TABLE spatial_ref_sys OWNER TO $db_user;'