---
- hosts: all
  sudo: yes
  sudo_user: postgres
  vars_files:
    - ../vars.yml

  tasks:
  - name: Ensure that postgresql server is running
    service: name=postgresql state=started

  - name: Ensure that postgis_template database exists
    postgresql_db: db=postgis_template state=present
    register: createdb_postgis_template

  - name: Make postgis_template a template
    command: psql -d postgis_template -c "UPDATE pg_database SET datistemplate=true WHERE datname='postgis_template';"
    only_if: '${createdb_postgis_template.changed}'

  - name: Create extension uuid-ossp on postgis_template
    command: psql -d postgis_template -c 'CREATE EXTENSION "uuid-ossp";'
    only_if: '${createdb_postgis_template.changed}'

  - name: Install postgis database extensions
    command: psql -d postgis_template -f /usr/share/postgresql/9.1/contrib/$item
    only_if: '${createdb_postgis_template.changed}'
    with_items:
      - postgis-1.5/postgis.sql
      - postgis-1.5/spatial_ref_sys.sql
      - postgis_comments.sql

  - name: Ensure that postgresql user '$db_user' exists
    postgresql_user: user=$db_user password=$db_user_pass

  - name: Ensure that all required databases exists
    postgresql_db: db=$db_name template='postgis_template' owner=$db_user

  - name: Ensure that '$db_user' is owned of '$db_name'
    command: psql -d $db_name -c 'ALTER TABLE geometry_columns OWNER TO $db_user; ALTER TABLE spatial_ref_sys OWNER TO $db_user;'

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted