---
- hosts: all
  sudo: yes
  vars:
    mirror: mirror://mirrors.ubuntu.com/mirrors.txt
    repo_components: main restricted universe multiverse

  tasks:
  - name: Install apt-add-repository to enable apt_repository module
    apt: pkg=python-software-properties update_cache=yes state=latest

  - name: Add additional repositories
    apt_repository: repo=$item
    with_items:
      - "'deb $mirror precise $repo_components'"
      - "'deb $mirror precise-updates $repo_components'"
      - "'deb $mirror precise-backports $repo_components'"
      - "'deb $mirror precise-security $repo_components'"
      - ppa:mapnik/v2.1.0

  - name: Install postgresql and postgis packages
    apt: pkg=$item update_cache=yes state=latest
    with_items:
      - postgresql-server-dev-9.1
      - postgresql-contrib-9.1
      - postgresql-9.1-postgis
      - python-psycopg2
      - phppgadmin
      - osm2pgsql
      - libmapnik
      - mapnik-utils